server:
  port: 12312

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fucking-cascade/backend-config
          searchPahts: '*'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/
